/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CmsPackage;

import java.awt.Image;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author Horine
 */
public class MemberDataImport extends javax.swing.JFrame {

    int insertedRows = 0;

    public MemberDataImport() {
        initComponents();
        scaleIcon1();
        scaleIcon2();
    }

    Statement St1 = null;
    ResultSet Rs1 = null;
    Connection con = null;
    DefaultTableModel model;

    private void scaleIcon1() {
        ImageIcon icon1 = new ImageIcon("C:\\Users\\host\\CMS\\src\\images\\logo3.png");
        //Scale iamge to fit the jbutton
        Image img = icon1.getImage();
        Image imgScale = img.getScaledInstance(jLabel_ICON1.getWidth(), jLabel_ICON1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon1 = new ImageIcon(imgScale);
        jLabel_ICON1.setIcon(scaledIcon1);
    }

    private void scaleIcon2() {
        ImageIcon icon2 = new ImageIcon("C:\\Users\\host\\CMS\\src\\images\\logo2.jpg");
        //Scale iamge to fit the jbutton
        Image img = icon2.getImage();
        Image imgScale = img.getScaledInstance(jLabel_ICON2.getWidth(), jLabel_ICON2.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon2 = new ImageIcon(imgScale);
        jLabel_ICON2.setIcon(scaledIcon2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_ICON1 = new javax.swing.JLabel();
        jLabel_ICON2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_MTable = new javax.swing.JTable();
        jButton_IMPORT = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton_INSERT_TO_DB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("IMPORTED MEMBERS DATA");

        jLabel_ICON1.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel_ICON1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(396, 396, 396)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 357, Short.MAX_VALUE)
                .addComponent(jLabel_ICON2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_ICON1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addContainerGap(52, Short.MAX_VALUE))
            .addComponent(jLabel_ICON2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTable_MTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "MEMBER_ID", "FIRSTNAME", "MIDDLE_NAME", "SURNAME", "GENDER", "DOB", "VILLAGE", "PHONE_NO", "MARITAL_STATUS", "OCCUPATION", "EMAIL", "RESIDENCE", "ADMISSION_DATE", "SACRAMENTAL_STATUS", "FATHER_NAME", "MOTHER_NAME", "MEMBER_GROUP", "MEMBER_ASSIGNMENT", "CHURCH_NAME"
            }
        ));
        jScrollPane1.setViewportView(jTable_MTable);

        jButton_IMPORT.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton_IMPORT.setForeground(new java.awt.Color(0, 153, 51));
        jButton_IMPORT.setText("Import (Excel)");
        jButton_IMPORT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_IMPORTActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 51, 51));
        jButton1.setText("Reset/Clear Rows");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton_INSERT_TO_DB.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButton_INSERT_TO_DB.setForeground(new java.awt.Color(0, 102, 255));
        jButton_INSERT_TO_DB.setText("Insert To DB");
        jButton_INSERT_TO_DB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_INSERT_TO_DBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(413, 413, 413)
                .addComponent(jButton_IMPORT)
                .addGap(71, 71, 71)
                .addComponent(jButton1)
                .addGap(73, 73, 73)
                .addComponent(jButton_INSERT_TO_DB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_IMPORT)
                    .addComponent(jButton1)
                    .addComponent(jButton_INSERT_TO_DB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    DefaultTableModel ImportDataFromExcelModel;
    private void jButton_IMPORTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_IMPORTActionPerformed
        // TODO add your handling code here:
        ImportDataFromExcelModel = (DefaultTableModel) jTable_MTable.getModel();

        //Clear JTable before importing excel file
        ImportDataFromExcelModel.setRowCount(0);

        //Default Directory path
        String currentDirectoryPath = "C:\\Users\\host\\Desktop";
        JFileChooser excelFileChooserImport = new JFileChooser(currentDirectoryPath);
        //Show only excel files
        FileNameExtensionFilter excelFileNameExtensionFilter = new FileNameExtensionFilter("EXCEL FILES", "xls", "xlsx", "xslm");
        excelFileChooserImport.setFileFilter(excelFileNameExtensionFilter);

        int excelChooser = excelFileChooserImport.showOpenDialog(null);

        //If open button is clicked
        if (excelChooser == JFileChooser.APPROVE_OPTION) {
            try {
                File excelFile = excelFileChooserImport.getSelectedFile();
                excelFIS = new FileInputStream(excelFile);
                excelBIS = new BufferedInputStream(excelFIS);
                excelImportWorkbook = new XSSFWorkbook(excelBIS);
                XSSFSheet excelSheet = excelImportWorkbook.getSheetAt(0);

                for (int i = 0; i <= excelSheet.getLastRowNum(); i++) {
                    XSSFRow excelRow = excelSheet.getRow(i);

                    XSSFCell excelImportedID = excelRow.getCell(0);
                    XSSFCell excelImportedFname = excelRow.getCell(1);
                    XSSFCell excelImportedMname = excelRow.getCell(2);
                    XSSFCell excelImportedSname = excelRow.getCell(3);
                    XSSFCell excelImportedGender = excelRow.getCell(4);
                    XSSFCell excelImportedDob = excelRow.getCell(5);
                    XSSFCell excelImportedVillage = excelRow.getCell(6);
                    XSSFCell excelImportedPhone = excelRow.getCell(7);
                    XSSFCell excelImportedMarital = excelRow.getCell(8);
                    XSSFCell excelImportedOccupation = excelRow.getCell(9);
                    XSSFCell excelImportedEmail = excelRow.getCell(10);
                    XSSFCell excelImportedResidence = excelRow.getCell(11);
                    XSSFCell excelImportedYrofAdm = excelRow.getCell(12);
                    XSSFCell excelImportedSacramental = excelRow.getCell(13);
                    XSSFCell excelImportedFather = excelRow.getCell(14);
                    XSSFCell excelImportedMother = excelRow.getCell(15);
                    XSSFCell excelImportedmGroup = excelRow.getCell(16);
                    XSSFCell excelImportedmAssign = excelRow.getCell(17);
                    XSSFCell excelImportedChurch = excelRow.getCell(18);

                    ImportDataFromExcelModel.addRow(new Object[]{excelImportedID, excelImportedFname, excelImportedMname, excelImportedSname, excelImportedGender, excelImportedDob, excelImportedGender, excelImportedPhone, excelImportedVillage,
                        excelImportedPhone, excelImportedMarital, excelImportedOccupation, excelImportedEmail, excelImportedResidence, excelImportedYrofAdm, excelImportedSacramental, excelImportedFather, excelImportedMother, excelImportedmGroup, excelImportedmAssign, excelImportedChurch});

                }
                JOptionPane.showMessageDialog(null, "Data imported successfully.!!");

            } catch (FileNotFoundException ex) {
                Logger.getLogger(UserData.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(UserData.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jButton_IMPORTActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int rowCount = ImportDataFromExcelModel.getRowCount();
        //int rowCount2 = model.getColumnCount();

        //JOptionPane.showMessageDialog(null, rowCount);
        //Remove JTable rows from 
        for (int i = rowCount - 1; i >= 0; i--) {
            ImportDataFromExcelModel.removeRow(i);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton_INSERT_TO_DBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_INSERT_TO_DBActionPerformed
        // TODO add your handling code here:
        int jTableRows = jTable_MTable.getRowCount();
        String SQlInsertDataImportedFromExcel = "INSERT INTO `members`(`FIRST_NAME`,`MIDDLE_NAME`,`SURNAME`,`GENDER`,`DOB`,`VILLAGE`,`PHONE_NO`,`MARITAL_STATUS`,`OCCUPATION`,`EMAIL`,`PLACE_OF_RESIDENCE`,`ADMISSION_DATE`,`SACRAMENTAL_STATUS`,`FATHER_NAME`,`MOTHER_NAME`,`MEMBER_GROUP`,`MEMBER_ASSIGNMENT`,`CHURCH_NAME`,`MEMBER_IMAGE`) "
                + "VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
        PreparedStatement pst;

        for (int i = 0; i < jTableRows; i++) {
            //String importedExcelID = ImportDataFromExcelModel.getValueAt(i, 0).toString();
            String importedExcelFname = ImportDataFromExcelModel.getValueAt(i, 1).toString();
            String importedExcelMname = ImportDataFromExcelModel.getValueAt(i, 2).toString();
            String importedExcelSname = ImportDataFromExcelModel.getValueAt(i, 3).toString();
            String importedExcelGender = ImportDataFromExcelModel.getValueAt(i, 4).toString();
            String importedExcelDob = ImportDataFromExcelModel.getValueAt(i, 5).toString();
            String importedExcelVillage = ImportDataFromExcelModel.getValueAt(i, 6).toString();
            String importedExcelPhone = ImportDataFromExcelModel.getValueAt(i, 7).toString();
            String importedExcelMarital = ImportDataFromExcelModel.getValueAt(i, 8).toString();
            String importedExcelOccupation = ImportDataFromExcelModel.getValueAt(i, 9).toString();
            String importedExcelEmail = ImportDataFromExcelModel.getValueAt(i, 10).toString();
            String importedExcelResidence = ImportDataFromExcelModel.getValueAt(i, 11).toString();
            String importedExcelYrofAdm = ImportDataFromExcelModel.getValueAt(i, 12).toString();
            String importedExcelSacramental = ImportDataFromExcelModel.getValueAt(i, 13).toString();
            String importedExcelFather = ImportDataFromExcelModel.getValueAt(i, 14).toString();
            String importedExcelMother = ImportDataFromExcelModel.getValueAt(i, 15).toString();
            String importedExcelmGroup = ImportDataFromExcelModel.getValueAt(i, 16).toString();
            String importedExcelmAssign = ImportDataFromExcelModel.getValueAt(i, 17).toString();
            String importedExcelChurch = ImportDataFromExcelModel.getValueAt(i, 18).toString();

            try {
                pst = CmsConnection.getConnection().prepareStatement(SQlInsertDataImportedFromExcel);
                pst.setString(1, importedExcelFname);
                pst.setString(2, importedExcelMname);
                pst.setString(3, importedExcelSname);
                pst.setString(4, importedExcelGender);
                pst.setString(5, importedExcelDob);
                pst.setString(6, importedExcelVillage);
                pst.setInt(7, Integer.parseInt(importedExcelPhone));
                pst.setString(8, importedExcelMarital);
                pst.setString(9, importedExcelOccupation);
                pst.setString(10, importedExcelEmail);
                pst.setString(11, importedExcelResidence);
                pst.setString(12, importedExcelYrofAdm);
                pst.setString(13, importedExcelSacramental);
                pst.setString(14, importedExcelFather);
                pst.setString(15, importedExcelMother);
                pst.setString(16, importedExcelmGroup);
                pst.setString(17, importedExcelmAssign);
                pst.setString(18, importedExcelChurch);

                int insertResult = pst.executeUpdate();

                if (insertResult > 0) {
                    insertedRows++;
                }
                JOptionPane.showMessageDialog(null, insertedRows + "Rows inserted");

            } catch (SQLException ex) {
                Logger.getLogger(UserData.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButton_INSERT_TO_DBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemberDataImport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MemberDataImport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_IMPORT;
    private javax.swing.JButton jButton_INSERT_TO_DB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_ICON1;
    private javax.swing.JLabel jLabel_ICON2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_MTable;
    // End of variables declaration//GEN-END:variables

    FileInputStream excelFIS = null;
    BufferedInputStream excelBIS = null;
    XSSFWorkbook excelImportWorkbook = null;

}
